language: python

sudo: required
dist: trusty

python:
  - "3.5"

cache:
  - bundler
  - apt
  - pip

install:
  - "sudo -H apt-get install python-dev -y"
  - "sudo -H apt-get install mecab libmecab-dev mecab-ipadic-utf8 -y"
  - "sudo -H pip install -r requirements.txt"
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/app/spec2test
script:
  - pytest ./app/test
