language: python

sudo: required
dist: trusty

python:
  - "3.6"

cache:
  - bundler
  - apt
  - pip

install:
  - "sudo -H apt-get install python-dev -y"
  - "git clone https://github.com/taku910/mecab.git"
  - "cd mecab/mecab"
  - "./configure  --enable-utf8-only"
  - "make"
  - "make check"
  - "sudo make install"
  - "cd ../mecab-ipadic"
  - "./configure --with-charset=utf8"
  - "make"
  - "sudo make install"
  - "sudo -H pip install -r requirements.txt"
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/app/spec2test
script:
  - pytest ./app/test
